 const product=
 [
  {
    "id": "P001",
    "name": "Classic Denim Jacket",
    "brand": "Levi's",
    "price": 79.99,
    "currency": "USD",
    "material": "100% Cotton Denim",
    "description": "A timeless denim jacket with a vintage look, perfect for all seasons.",
    "image": require('./assets/denim.jpg'),
    "size": ["S", "M", "L", "XL"],
    "color": "Blue",
    "gender": "Unisex",
    "stock": 34,
    "category": "Jackets",
    "rating": 4.5
  },
  {
    "id": "P002",
    "name": "Men's Slim Fit Chinos",
    "brand": "H&M",
    "price": 39.99,
    "currency": "USD",
    "material": "98% Cotton, 2% Elastane",
    "description": "Comfortable slim fit chinos with stretch, ideal for everyday wear.",
    "image": "https://example.com/images/slim-fit-chinos.jpg",
    "size": ["30", "32", "34", "36"],
    "color": "Beige",
    "gender": "Male",
    "stock": 21,
    "category": "Pants",
    "rating": 4.2
  },
  {
    "id": "P003",
    "name": "Women's Floral Maxi Dress",
    "brand": "Zara",
    "price": 59.99,
    "currency": "USD",
    "material": "100% Rayon",
    "description": "Flowy floral printed dress with V-neckline and waist tie. Great for summer.",
    "image": "https://example.com/images/floral-maxi-dress.jpg",
    "size": ["XS", "S", "M", "L"],
    "color": "Multicolor",
    "gender": "Female",
    "stock": 15,
    "category": "Dresses",
    "rating": 4.7
  },
  {
    "id": "P004",
    "name": "Unisex Cotton Graphic T-Shirt",
    "brand": "Nike",
    "price": 29.99,
    "currency": "USD",
    "material": "100% Organic Cotton",
    "description": "Soft graphic tee with breathable fabric, perfect for casual wear.",
    "image": "https://example.com/images/graphic-tee.jpg",
    "size": ["S", "M", "L", "XL", "XXL"],
    "color": "Black",
    "gender": "Unisex",
    "stock": 50,
    "category": "T-Shirts",
    "rating": 4.3
  },
  {
    "id": "P005",
    "name": "Sports Zip Hoodie",
    "brand": "Adidas",
    "price": 64.99,
    "currency": "USD",
    "material": "Polyester Blend",
    "description": "Athletic zip hoodie with breathable fabric and classic fit.",
    "image": "https://example.com/images/zip-hoodie.jpg",
    "size": ["S", "M", "L", "XL"],
    "color": "Gray",
    "gender": "Unisex",
    "stock": 27,
    "category": "Hoodies",
    "rating": 4.6
  },
  {
    "id": "P006",
    "name": "Kids Cotton Pajama Set",
    "brand": "Gap Kids",
    "price": 25.99,
    "currency": "USD",
    "material": "100% Cotton",
    "description": "Comfy and breathable pajamas with cartoon prints for kids.",
    "image": "https://example.com/images/kids-pajama.jpg",
    "size": ["2Y", "4Y", "6Y", "8Y"],
    "color": "Yellow",
    "gender": "Kids",
    "stock": 45,
    "category": "Sleepwear",
    "rating": 4.8
  },
  {
    "id": "P007",
    "name": "Formal White Shirt",
    "brand": "Arrow",
    "price": 42.50,
    "currency": "USD",
    "material": "Cotton Blend",
    "description": "Slim-fit formal shirt with full sleeves and button cuffs.",
    "image": "https://example.com/images/formal-white-shirt.jpg",
    "size": ["38", "40", "42", "44"],
    "color": "White",
    "gender": "Male",
    "stock": 19,
    "category": "Shirts",
    "rating": 4.1
  },
  {
    "id": "P008",
    "name": "Women's Workout Leggings",
    "brand": "Puma",
    "price": 35.00,
    "currency": "USD",
    "material": "Polyester and Elastane",
    "description": "High-rise leggings with sweat-wicking technology.",
    "image": "https://example.com/images/workout-leggings.jpg",
    "size": ["S", "M", "L"],
    "color": "Purple",
    "gender": "Female",
    "stock": 32,
    "category": "Activewear",
    "rating": 4.4
  },
  {
    "id": "P009",
    "name": "Boys Printed Hoodie",
    "brand": "Uniqlo",
    "price": 29.50,
    "currency": "USD",
    "material": "Cotton Blend",
    "description": "Cozy hoodie with superhero print, soft on skin and warm.",
    "image": "https://example.com/images/boys-hoodie.jpg",
    "size": ["6Y", "8Y", "10Y"],
    "color": "Red",
    "gender": "Kids",
    "stock": 40,
    "category": "Hoodies",
    "rating": 4.6
  },
  {
    "id": "P010",
    "name": "Women's Woolen Overcoat",
    "brand": "Mango",
    "price": 120.00,
    "currency": "USD",
    "material": "Wool Blend",
    "description": "Elegant wool overcoat for winter with double-breasted design.",
    "image": "https://example.com/images/woolen-overcoat.jpg",
    "size": ["S", "M", "L"],
    "color": "Camel",
    "gender": "Female",
    "stock": 12,
    "category": "Coats",
    "rating": 4.9
  },
  {
    "id": "P011",
    "name": "Men's Casual Checked Shirt",
    "brand": "Tommy Hilfiger",
    "price": 54.90,
    "currency": "USD",
    "material": "100% Cotton",
    "description": "Button-down checked shirt for men, ideal for casual or smart-casual wear.",
    "image": "https://example.com/images/checked-shirt.jpg",
    "size": ["M", "L", "XL"],
    "color": "Red & Navy",
    "gender": "Male",
    "stock": 25,
    "category": "Shirts",
    "rating": 4.3
  },
  {
    "id": "P012",
    "name": "Women's Ethnic Kurti",
    "brand": "Biba",
    "price": 45.00,
    "currency": "USD",
    "material": "Cotton & Rayon Blend",
    "description": "Traditional printed kurti with three-quarter sleeves and round neck, perfect for festive or daily ethnic wear.",
    "image": "https://example.com/images/ethnic-kurti.jpg",
    "size": ["S", "M", "L", "XL"],
    "color": "Green",
    "gender": "Female",
    "stock": 30,
    "category": "Ethnic Wear",
    "rating": 4.5
  }
]


export default product
